### ISSUE TITLE
Introduce EKS add-ons

### ISSUE THREAD

**Issue by lnovara** [sighupio/fury-eks-installer#32]
Upgrading an EKS cluster does not update core components that come with the cluster such as vpc-cni, coredns and kube-proxy.

In the past, this required to pull the updated Kubernetes resources for such components and applying them to the cluster. Now, AWS introduced EKS add-ons to address this issue thus allowing the upgrade of such components in a straightforward way.

I think we should add this feature (available since EKS v1.18) to improve day-2 operations management.

Ref:
  - https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html

Todo list:

- [ ] Remove from furyctl the patch on coredns (in the tf kubernetes project), and move the tolerations/selector using terraform variables
- [x] Relax aws provider requirement on all tf modules on core modules
- [ ] Test the upgrade between 1.25 to 1.26 (the target version for eks addons is 1.26)
  - [ ] Check storageclasses while using the add-ons EBS csi driver (the ebs one should be default)

**Comment by lnovara** [comment]
Corresponding `furyctl` issue: sighupio/furyctl#69

**Comment by ralgozino** [comment]
The EKS add-ons because they are somehow limited (for example they don't support tolerations), it would be better to maintain our own set of manifests for these components.

**Comment by ralgozino** [comment]
AWS just announced this that maybe is useful:

https://aws.amazon.com/blogs/aws/new-aws-marketplace-for-containers-now-supports-direct-deployment-to-amazon-eks-clusters/

**Comment by lzecca78** [comment]
Hi, regarding this implementation, now is becoming mandatory because from 1 July 2023, will be deprecated the doc of  the self-managed addon installation as written here:

https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html
https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html


me and @FedericoAntoniazzi tried to deepen the migration between the 2 setups (self-managed and eks) but we haven't yet found a valid solution. I don't think that this means that they will deprecate very soon the self-managed, but for sure is a step in that direction.

**Comment by omissis** [comment]
closing, as it was done within fury-distro and furyctl
